springdoc:
 swagger-ui:
  path: /swagger.html

verify:
  proxy:
       baseUrl: http://gw-ibm-verify-service.biz-common-dev.svc.cluster.local:8080
#       baseUrl: https://iamlab.apps.nprd.ubidp.local
       registrationEndpoint: /mga/sps/apiauthsvc/policy/mbregistration
       setMPinEndpoint: /mga/sps/apiauthsvc/policy/setloginpin
       setTpinEndpoint: /mga/sps/apiauthsvc/policy/settpin
       setPasswordEndpoint: /mga/sps/apiauthsvc/policy/setpassword
       securityQuestionEndpoint: /mga/sps/apiauthsvc/policy/updateknowledgequestions
       corpUserRegistrationEndpoint: /mga/sps/apiauthsvc/policy/corpRegistration
